apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: helm-demo-app
    apps.tanzu.vmware.com/has-tests: "true"
  name: helm-demo-app
  namespace: tap-sit
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/sample-accelerators/tanzu-java-web-app
  params:
  - name: chart_name
    value: tap
  - name: chart_values
    value:
      workloadname: helm-demo-app
  - name: chart_repo
    value:
      kind: HelmRepository
      name: timwang-github
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: vmware-approvaltask
  - name: integration_testing_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: int-test