apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    apps.tanzu.vmware.com/aggregate-to-deliverable: "true"
  name: tap-helm-addition-role
rules:
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - helmcharts
  - helmrepositories
  verbs:
  - "*"