apiVersion: carto.run/v1alpha1
kind: ClusterConfigTemplate
metadata:
  labels:
    app.tanzu.vmware.com/deliverable-type: helm
  name: config-template-helm
spec:
  configPath: .data
  healthRule:
    alwaysHealthy: {}
  ytt: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:assert", "assert")
    #@ load("@ytt:yaml", "yaml")
    #@ load("@ytt:struct", "struct")
    #@ load("@ytt:overlay", "overlay")

    #@ def merge_labels(fixed_values):
    #@   labels = {}
    #@   if hasattr(data.values.workload.metadata, "labels"):
    #@     labels.update(data.values.workload.metadata.labels)
    #@   end
    #@   labels.update(fixed_values)
    #@   return labels
    #@ end

    #@ def is_monorepo_approach():
    #@   if 'gitops_server_address' in data.values.params and 'gitops_repository_owner' in data.values.params and 'gitops_repository_name' in data.values.params:
    #@     return True
    #@   end
    #@   if 'gitops_server_address' in data.values.params or 'gitops_repository_owner' in data.values.params or 'gitops_repository_name' in data.values.params:
    #@     'gitops_server_address' in data.values.params or assert.fail("missing param: gitops_server_address")
    #@     'gitops_repository_owner' in data.values.params or assert.fail("missing param: gitops_repository_owner")
    #@     'gitops_repository_name' in data.values.params or assert.fail("missing param: gitops_repository_name")
    #@   end
    #@   return False
    #@ end

    #@ def has_git_params():
    #@   if 'gitops_repository_prefix' in data.values.params:
    #@     return True
    #@   end
    #@
    #@   if 'gitops_repository' in data.values.params:
    #@     return True
    #@   end
    #@
    #@   return False
    #@ end

    #@ def is_gitops():
    #@   return is_monorepo_approach() or has_git_params()
    #@ end

    #@ def param(key):
    #@   if not key in data.values.params:
    #@     return None
    #@   end
    #@   return data.values.params[key]
    #@ end

    #@ def strip_trailing_slash(some_string):
    #@   if some_string[-1] == "/":
    #@     return some_string[:-1]
    #@   end
    #@   return some_string
    #@ end

    #@ def mono_repository():
    #@   strip_trailing_slash(data.values.params.gitops_server_address)
    #@   return "/".join([
    #@     strip_trailing_slash(data.values.params.gitops_server_address),
    #@     strip_trailing_slash(data.values.params.gitops_repository_owner),
    #@     data.values.params.gitops_repository_name,
    #@   ]) + ".git"
    #@ end

    #@ def git_repository():
    #@   if is_monorepo_approach():
    #@     return mono_repository()
    #@   end
    #@
    #@   if 'gitops_repository' in data.values.params:
    #@     return param("gitops_repository")
    #@   end
    #@
    #@   prefix = param("gitops_repository_prefix")
    #@   return prefix + data.values.workload.metadata.name + ".git"
    #@ end

    #@ def image():
    #@   return "/".join([
    #@    data.values.params.registry.server,
    #@    data.values.params.registry.repository,
    #@    "-".join([
    #@      data.values.workload.metadata.name,
    #@      data.values.workload.metadata.namespace,
    #@      "bundle",
    #@    ])
    #@   ]) + ":" + data.values.workload.metadata.uid
    #@ end

    #@ def chart_values():
    #@ if hasattr(data.values.params, "chart_values"):
    #@overlay/match-child-defaults missing_ok=True
    #@ chart_values_computed = overlay.apply(data.values.params,image_path())
    #@ return struct.encode(yaml.decode(yaml.encode(chart_values_computed))).chart_values
    #@ else:
    #@ return struct.encode(yaml.decode(yaml.encode(image_path()))).chart_values
    #@ end
    #@ end

    #@ def image_path():
    #@overlay/match-child-defaults missing_ok=True
    chart_values:
      #@overlay/match-child-defaults missing_ok=True
      image:
        #@overlay/match-child-defaults missing_ok=True
        repository: #@ data.values.images.image.image
    #@ end

    #@ def helm_release():
    ---
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: #@ data.values.workload.metadata.name
      namespace: #@ data.values.workload.metadata.namespace
      labels: #@ merge_labels({ "app.kubernetes.io/component": "helm-release", "app.tanzu.vmware.com/release-type": "helm" })
    spec:
      interval: 5m
      chart:
        spec:
          chart: #@ data.values.params.chart_name
          #@ if/end hasattr(data.values.params, "chart_version"):
          version: #@ data.values.params.chart_version
          sourceRef:
            kind: #@ data.values.params.chart_repo.kind
            name: #@ data.values.params.chart_repo.name
            #@ if/end hasattr(data.values.params.chart_repo, "namespace"):
            namespace: #@ data.values.params.chart_repo.namespace
          interval: 1m
      upgrade:
        remediation:
          remediateLastFailure: true
      values: #@ chart_values()
    #@ end
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: #@ "{}-helm-release".format(data.values.workload.metadata.name)
    labels: #@ merge_labels({ "app.kubernetes.io/component": "config" })
    data:
      helm-release.yaml: #@ yaml.encode(helm_release())
