apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: helm-controller.fluxcd.community.tanzu.vmware.com.0.17.2
spec:
  refName: helm-controller.fluxcd.community.tanzu.vmware.com
  version: 0.17.2
  releasedAt: 2022-05-01T16:40:55Z
  capacityRequirementsDescription: ""
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: "{harbor-url}/{project-name}/fluxcd-helm-controller-bundle:0.17.2"
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
  valuesSchema:
    openAPIv3:
      properties:
        namespace:
          type: string
          description: Deployment and service namespace
          default: helm-system
        limits_cpu:
          type: string
          description: Set cpu usuage limit
          default: 1000m
        limits_memory:
          type: string
          description: Set memory usuage limit
          default: 1Gi
